"""Code framework nodes - now generated from registry."""
# Most nodes are now generated by app/nodes/generator.py
# pot.py is kept as a special node with sandbox execution logic

from .pot import program_of_thoughts_node

__all__ = ["program_of_thoughts_node"]
